### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "wjdrlfgg@test.com",
  "password": "1Q2W3E4R"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/71

### Find all users with a given email
GET http://localhost:3000/auth?email=test@test.com

### Delete a user given id
DELETE  http://localhost:3000/auth/69

### Update a user
PATCH  http://localhost:3000/auth/71
Content-Type: application/json

{
  "email": "test@testt.com",
  "password": "1Q2W3Eqwe"
}